### ISSUE TITLE
 Varying variables with precision qualifiers are mangled

### ISSUE THREAD

**Issue by mariusgabris** [leosingleton/webpack-glsl-minify#21]
Hi Leo, 

I've noticed a bug in some of our shaders where in the vertex code we specify the precision qualifiers for a varying.

**Input:** 
varying highp vec3 someName;
**Expected result:**
varying highp vec3 someName;
**Actual result:**
varying highp vec3 A;

As a workaround, those can be specified with @nomangle.
if you want I can have look at it and create a PR.

**Comment by leosingleton** [comment]
Hi Marius, when you have a chance, try the fix in this branch: https://github.com/leosingleton/webpack-glsl-minify/tree/bugfix/precision

The fix was a bit larger than I would have liked, but varying was only one specific case where precision qualifiers caused problems.

**Comment by mariusgabris** [comment]
Hi Leo, I finally got the chance to test the fix, it works perfectly on my set of shaders. Great work!

**Comment by leosingleton** [comment]
Great! I went ahead and included it in the latest NPM release as the same code change also fixed a different bug I had. I'll close this one out.
