### ISSUE TITLE
Support esModule option

### ISSUE THREAD

**Issue by Hersir88** [leosingleton/webpack-glsl-minify#28]
Could you please add esModule option like in [raw-loader](https://github.com/webpack-contrib/raw-loader/blob/master/src/index.js);

As right now its not possible to import glsl files, like this

`import shader from "./shader.glsl"`;

Ideally would be nice to support both source and object options with esModules.

Example fix for source option in minify.ts for esModules:
```
case 'source':
          return 'export default ' + GlslMinify.stringify(program.sourceCode);
```

**Comment by leosingleton** [comment]
Added in 1.4.0.

Note that unlike raw-loader, the esModule option is disabled by default to be backwards-compatible with the other 1.x.x versions.

**Comment by Hersir88** [comment]
@leosingleton thank you will try out

**Comment by Hersir88** [comment]
Tests and works as expected
