### ISSUE TITLE
Incorrect mangling where there is more than one @const

### ISSUE THREAD

**Issue by darkhus** [leosingleton/webpack-glsl-minify#33]
Hi,
I found that when there is more that one @const inside shader file, then mangled shader is incorect, and its imposible to assign value for const and compile shader.

Example:
I got three consts inside my shader:
```c
@const int sizeOfSliceInsideAtlas
@const int zSlicesCount
@const int zSlicesNormalTexCount
```
and mangles shader is:
```c
const int A=$0$;const int B=int zSlicesCount$;const int C=$2$;
```

**Comment by leosingleton** [comment]
Found the issue... Released version 1.4.1 with the fix.
