### ISSUE TITLE
glsl keyword that should not get mangled

### ISSUE THREAD

**Issue by CraigglesO** [leosingleton/webpack-glsl-minify#40]
```glsl
#version 300 es
precision highp float;

layout (location = 0) in vec2 aPos;
layout (location = 6) in float aRadius;
layout (location = 7) in float aIndex;
```

this package should ignore keyword "location"
edit - sorry OR "layout"

these are WebGL2 standards so that's probably why it was never added.

**Comment by leosingleton** [comment]
You're correct... I haven't done any testing with WebGL2.

The minifier doesn't fully parse GLSL, so you can likely work around it by simply add the keywords to the nomangle array. Is the output correct if you add the `@nomangle layout location` directive or set the "nomangle" array in the loader options?

**Comment by CraigglesO** [comment]
Yeah, after posting this I figured out the `@nomangle` and it worked perfect. Really great package, thank you.
