### ISSUE TITLE
Only export the source code

### ISSUE THREAD

**Issue by kocsis1david** [leosingleton/webpack-glsl-minify#6]
It would be nice if there were an option to only export the `sourceCode` from the output.

I wrote a simple loader that extracts the `sourceCode` and I set the `preserveUniforms` option to true. This makes the bundle smaller, because it won't contain the minified uniform name mappings.

**Comment by leosingleton** [comment]
Good idea. Let me see if I can get this into the next update. I hadn't included `preserveUniforms` in the README yet, as I've only used it for debugging, but I see how this could be useful.

**Comment by leosingleton** [comment]
Added in version 1.2.0. Use the `output: 'source'` option in the loader config.

**Comment by kocsis1david** [comment]
nice, thanks

**Comment by kocsis1david** [comment]
https://github.com/leosingleton/webpack-glsl-minify/blob/master/src/minify.ts#L661

This should be `module.exports` I think, instead of `modules.export`.

**Comment by leosingleton** [comment]
Yes, you're right. Released 1.2.1 with the fix.
